spring:
  application:
    name: taskservice

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  logging:
#    level:
#      org.springframework: INFO
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#  app:
##    Remove jet secret while deploying
#    jwtSecret: ${JWT_SECRET:diccxFxb7GQABoDcN0EmqGvjMr6SBpAUfM7Lt+AdscE=}
#    jwtExpirationMs: 86400000 # 24 hours
#    jwtRefreshExpirationMs: 604800000 # 7 days
#
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 1234567890-abcde12345fghij67890klmnopqrst.apps.googleusercontent.com
#            client-secret: GOCSPX-ABCDefGhiJKlmnOpQRsTUVwxyz1234
#            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/google"
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: email
#
  management:
    endpoints:
      web:
        base-path: /actuator
        exposure:
          include: health, metrics, prometheus
    endpoint:
      health:
        show-details: always